services:
  app:
    build:
      context: ../.
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../src:/app
    ports:
      - '8000:8000'
    networks:
      - vs_network

  https-portal:
    depends_on:
      - app
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'localhost -> http://app:8000'
      STAGE: 'local' # Don't use production until staging works
    volumes:
      - https-portal-data:/var/lib/https-portal
    networks:
      - vs_network

volumes:
    https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL

networks:
  vs_network:
