services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    networks:
      - app_network

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network: